updated the readme, made some sanity tests in the script

diff --git a/usr/bin/debianize-android-rom b/usr/bin/debianize-android-rom
--- a/usr/bin/debianize-android-rom
+++ b/usr/bin/debianize-android-rom
@@ -12,37 +12,37 @@ select_drive(){
 	options=$1
 	c=0
 	for o in $options; do
-	    options_list="$o
+		options_list="$o
 $options_list"
-	    c=$((c+1))
+		c=$((c+1))
 	done
 	echo "$title
 	$prompt
 	"
 	PS3="$prompt "
 	select opt in "${options[@]}" "Quit"; do 
-	    case "$REPLY" in
-	    1 ) export DRIVE="$opt" && break;;
-	    2 ) export DRIVE="$opt" && break;;
-	    3 ) export DRIVE="$opt" && break;;
-	    4 ) export DRIVE="$opt" && break;;
-	    5 ) export DRIVE="$opt" && break;;
-	    6 ) export DRIVE="$opt" && break;;
-	    7 ) export DRIVE="$opt" && break;;
-	    8 ) export DRIVE="$opt" && break;;
-	    9 ) export DRIVE="$opt" && break;;
-            $(( ${#options[@]}+1 )) ) export DRIVE="QUIT" && echo "Goodbye!"; break;;
-	    *) export DRIVE="Invalid option.";continue;;
-	    esac
+		case "$REPLY" in
+		1 ) export DRIVE="$opt" && break;;
+		2 ) export DRIVE="$opt" && break;;
+		3 ) export DRIVE="$opt" && break;;
+		4 ) export DRIVE="$opt" && break;;
+		5 ) export DRIVE="$opt" && break;;
+		6 ) export DRIVE="$opt" && break;;
+		7 ) export DRIVE="$opt" && break;;
+		8 ) export DRIVE="$opt" && break;;
+		9 ) export DRIVE="$opt" && break;;
+		$(( ${#options[@]}+1 )) ) export DRIVE="QUIT" && echo "Goodbye!"; break;;
+		*) export DRIVE="Invalid option.";continue;;
+		esac
 	done
 	cd "$WD"
 }
 check_drive(){
 	cd "$WD"
 	if [ "$DRIVE" == "QUIT" ]; then
-	    exit 0
+		exit 0
 	else
-	    echo "$DRIVE"
+		echo "$DRIVE"
 	fi
 	cd "$WD"
 }
@@ -65,12 +65,12 @@ you have selected the incorrect drive. Please verify that you wish to format
 before continuing.
 "
 	read -p "	Is this the correct device(Y/N)? " -n 1 -r
-	echo    # (optional) move to a new line
+	echo	# (optional) move to a new line
 	if [[ $REPLY =~ ^[Yy]$ ]]; then
-	    make_aligned_partitions
+		make_aligned_partitions
 	else
-	    echo "User cancelled, incorrect disk."
-	    exit 0
+		echo "User cancelled, incorrect disk."
+		exit 0
 	fi
 	cd "$WD"
 }
@@ -104,23 +104,28 @@ exec /sbin/busybox switch_root /mnt/root /etc/init
 #$ANDROID_INITRAMFS[8]
 	mkdir $NEWINITRAMFS && cd $NEWINITRAMFS && mkdir -p proc sys dev mnt/root sbin
 	echo "$SLASHINIT" > init
+	chmod a+x init
 	export ARCH="arm"
 	export CROSS_COMPILE="arm-linux-gnueabihf-"
-	apt-get source -b busybox-static:armhf
-	apt-get 
+	if [ -f busybox*/build/static/busybox]; then
+		apt-get source -b busybox-static:armhf
+	fi
 	cp busybox*/build/static/busybox sbin/busybox
 	chmod a+x init sbin/busybox
 	find . | cpio --quiet -H newc -o | gzip > ../initramfs.cpio.gz
 	cd ..
 	if [ -f boot.img ]; then
-	    abootimg -x boot.img
-	    if [ -f linux-source-3.16.tar.xz ]; then
-	        tar xf /usr/src/linux-source-3.16.tar.xz
-	        export $($WD/linux-source-3.16/scripts/extract-ikconfig zImage | grep PHYS_OFFSET)
-	    fi
+		abootimg -x boot.img
+		if [ -f /usr/src/linux-source-3.16.tar.xz ]; then
+			tar xf /usr/src/linux-source-3.16.tar.xz
+			export $($WD/linux-source-3.16/scripts/extract-ikconfig zImage | grep PHYS_OFFSET)
+		else
+			apt-get source -b linux-source-3.16
+			export $($WD/linux-source-3.16/scripts/extract-ikconfig zImage | grep PHYS_OFFSET)
+		fi
 	else
-	    echo "Error, original kernel not found. Place boot.img in working directory."
-	    exit 1
+		echo "Error, original kernel not found. Place boot.img in working directory."
+		exit 1
 	fi
 	abootimg -u boot.img -c [ "CONFIG_PHYS_OFFSET=$PHYS_OFFSET" ] -k zImage -r initramfs.cpio.gz
 	cd "$WD"
@@ -198,7 +203,8 @@ export PATH=/sbin:/usr/sbin:/bin:/usr/bin
 /sbin/busybox echo \"\`/sbin/busybox date\` All done\"
 exit 0" > /etc/init.stage2
 	chmod a+x /etc/init.stage2
-	echo "/etc/init.d/hostname.sh start
+	echo "#!/bin/sh -e
+/etc/init.d/hostname.sh start
 /etc/init.d/ssh start
 exit 0" > /etc/rc.local
 	chmod a+x /etc/rc.local
